CREATE TABLE IF NOT EXISTS chat_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    send_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sender VARCHAR(50) NOT NULL,
    receiver VARCHAR(50),
    message TEXT NOT NULL
    );